export const POST_ADD = 'POST_ADD'
export const POST_VOTE = 'POST_VOTE'
export const POST_DELETE = 'POST_DELETE'
export const COMMENT_ADD = 'COMMENT_ADD'
export const COMMENT_VOTE = 'COMMENT_VOTE'
export const COMMENT_DELETE = 'COMMENT_DELETE'
